### ISSUE TITLE
RT

### ISSUE THREAD

**Issue by xiaofu-15191** [danielqfmai/QQEmojiRenderer#2]
![image](https://github.com/user-attachments/assets/71c4d8c2-623f-4d3e-a92d-78a695bae098)

**Comment by danielqfmai** [comment]
?

**Comment by danielqfmai** [comment]
你拷到了哪个文件夹

**Comment by danielqfmai** [comment]
download_requirements.sh会下载三个文件

**Comment by danielqfmai** [comment]
算了，加release了
